name: KnPing CI & CD

on:
 push:
   branches: [ master ]
 workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14
      uses: actions/setup-node@v2
      with:
        node-version: '14'
        cache: 'npm'
    - run: npm install
    - run: npm run build --if-present
    - name: scp-action
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SCP_HOST }}
        username: ${{ secrets.SCP_USER }}
        password: ${{ secrets.SCP_PASSWORD }}
        port: ${{ secrets.SCP_PORT }}
        source: "build/asset-manifest.json, build/favicon.ico, build/index.html, build/logo192.png, build/logo512.png, build/manifest.json, build/robots.txt, build/static"
        strip_components: 1
        target: "/var/www/html"
     
